USE pong;

DROP TABLE IF EXISTS game;

CREATE TABLE game (
  id INT NOT NULL AUTO_INCREMENT,
  time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  l SMALLINT NOT NULL,
  r SMALLINT NOT NULL,
  lp SMALLINT NOT NULL,
  rp SMALLINT NOT NULL,
  PRIMARY KEY (id),
  KEY (l),
  KEY (r),
  KEY (time)
);
